title: Shubham Kumar
subtitle: Computer Science and Engineerimg
description: >- # this means to ignore newlines until "baseurl:"

author: Shubham Kumar
mobile: +91-7599246005
email: shubham.kumar@engineer.com
avatar: assets/images/avatar.jpg


baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
